### ISSUE TITLE
BandUnlocker.exe not working; archive/apps/Windows Apps/BandUnlocker.exe

### ISSUE THREAD

**Issue by horyzen1** [MicrosoftBandDev/archive#2]
When I download and open BandUnlocker.exe, it says that the app is deactivated. Have done some research, and it has been deactivated in the past before but got fixed. Any way to fix it now?

**Comment by Pdawg-bytes** [comment]
Working on it ;)

**Comment by horyzen1** [comment]
Ok, the developer has fixed the problem, everything working as normal 😅 So far, I have encountered no problems.
